server:
  port: 8080

spring:
  application:
    name: config-server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/hoang1533/cloud-config-server
          default-label: main
        bootstrap: false